import { execFileSync } from 'node:child_process';
import { writeFileSync, readFileSync, unlinkSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir, platform } from 'node:os';
import { fileURLToPath } from 'node:url';
import { success, failure, warn, dim } from './output.js';

const SERVICE_NAME = 'vibe-usage';
const LAUNCHD_LABEL = 'ai.vibecafe.vibe-usage';

function detectPlatform() {
  const os = platform();
  if (os === 'linux') {
    if (existsSync('/run/systemd/system')) return 'systemd';
    return null;
  }
  if (os === 'darwin') {
    return 'launchd';
  }
  if (os === 'win32') {
    return 'taskscheduler';
  }
  return null;
}

function resolvePaths() {
  const nodePath = process.execPath;
  const thisFile = fileURLToPath(import.meta.url);
  const binPath = join(thisFile, '..', '..', 'bin', 'vibe-usage.js');

  // npx cache paths are unstable — service will break when cache is cleared.
  // POSIX: ~/.npm/_npx/<hash>/...; Windows: %LocalAppData%\npm-cache\_npx\...
  const isNpxCache = /[\\/]_npx[\\/]/.test(binPath);

  return { nodePath, binPath, isNpxCache };
}

function getServicePaths(plat) {
  if (plat === 'systemd') {
    const dir = join(homedir(), '.config', 'systemd', 'user');
    return { dir, file: join(dir, `${SERVICE_NAME}.service`) };
  }
  if (plat === 'launchd') {
    const dir = join(homedir(), 'Library', 'LaunchAgents');
    return { dir, file: join(dir, `${LAUNCHD_LABEL}.plist`) };
  }
  if (plat === 'taskscheduler') {
    const dir = join(homedir(), '.vibe-usage');
    return {
      dir,
      file: join(dir, 'daemon-task.xml'),
      cmd: join(dir, 'daemon-task.cmd'),
      vbs: join(dir, 'daemon-task.vbs'),
    };
  }
  return null;
}

function escapeSystemdEnvironment(value) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

// In `set "KEY=VALUE"`, cmd expands %VAR% on the line, so literal percents must double
function escapeCmdValue(value) {
  return value.replace(/%/g, '%%');
}

function psString(value) {
  return `'${value.replace(/'/g, "''")}'`;
}

function escapeXml(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

const PRESERVED_SERVICE_ENV = ['MIMOCODE_HOME', 'MIMOCODE_DB', 'XDG_DATA_HOME'];

function serviceEnvironment(claudeConfigDir, env) {
  const values = {
    CLAUDE_CONFIG_DIR: claudeConfigDir,
    ...Object.fromEntries(PRESERVED_SERVICE_ENV.map(key => [key, env[key]?.trim()])),
  };
  return Object.entries(values).filter(([, value]) => value);
}

export function generateSystemdUnit(
  nodePath,
  binPath,
  claudeConfigDir = process.env.CLAUDE_CONFIG_DIR?.trim(),
  env = process.env,
) {
  const environment = serviceEnvironment(claudeConfigDir, env)
    .map(([key, value]) => `Environment="${key}=${escapeSystemdEnvironment(value)}"\n`)
    .join('');
  return `[Unit]
Description=VibeCafe Usage Tracker
After=network.target

[Service]
Type=simple
ExecStart=${nodePath} ${binPath} daemon
Restart=on-failure
RestartSec=10
Environment=NODE_ENV=production
${environment}WorkingDirectory=${homedir()}

[Install]
WantedBy=default.target
`;
}

export function generateLaunchdPlist(
  nodePath,
  binPath,
  claudeConfigDir = process.env.CLAUDE_CONFIG_DIR?.trim(),
  env = process.env,
) {
  const logDir = join(homedir(), '.vibe-usage');
  const environment = serviceEnvironment(claudeConfigDir, env)
    .map(([key, value]) => `        <key>${key}</key>\n        <string>${escapeXml(value)}</string>\n`)
    .join('');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LAUNCHD_LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${nodePath}</string>
        <string>${binPath}</string>
        <string>daemon</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>${homedir()}</string>
    <key>StandardOutPath</key>
    <string>${join(logDir, 'daemon.log')}</string>
    <key>StandardErrorPath</key>
    <string>${join(logDir, 'daemon.err')}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>NODE_ENV</key>
        <string>production</string>
${environment}    </dict>
</dict>
</plist>
`;
}

export function generateWindowsTaskCmd(
  nodePath,
  binPath,
  claudeConfigDir = process.env.CLAUDE_CONFIG_DIR?.trim(),
  env = process.env,
) {
  const logPath = join(homedir(), '.vibe-usage', 'daemon.log');
  const lines = [
    '@echo off',
    'rem Generated by `vibe-usage daemon install` - reinstalling overwrites this file',
    'set "NODE_ENV=production"',
  ];
  for (const [key, value] of serviceEnvironment(claudeConfigDir, env)) {
    lines.push(`set "${key}=${escapeCmdValue(value)}"`);
  }
  lines.push(
    `"${escapeCmdValue(nodePath)}" "${escapeCmdValue(binPath)}" daemon >> "${escapeCmdValue(logPath)}" 2>&1`,
  );
  return lines.join('\r\n') + '\r\n';
}

export function generateWindowsTaskVbs(cmdPath) {
  const lines = [
    "' Vibe Usage daemon launcher - window style 0 keeps the logon session console-free;",
    "' waitOnReturn=True keeps the task's Running state true to the daemon's lifetime",
    "' (so MultipleInstancesPolicy can veto a second start while one daemon lives)",
    `CreateObject("WScript.Shell").Run """${cmdPath}""", 0, True`,
  ];
  return lines.join('\r\n') + '\r\n';
}

// Task Scheduler kills tasks after its default 72h execution limit unless the XML
// pins ExecutionTimeLimit to PT0S — the daemon is meant to run indefinitely.
// Registered via `Register-ScheduledTask -Xml`: `schtasks /create /sc onlogon`
// demands elevation, while a self-scoped LogonTrigger does not (verified non-admin).
// The declaration must say UTF-16 or the Task Scheduler COM parser rejects the
// registration with an XML format error, even though the string handed to
// Register-ScheduledTask is read from the UTF-8 file via Get-Content -Raw.
export function generateWindowsTaskXml(userId, wscriptPath, vbsPath) {
  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>VibeCafe Usage Tracker background sync daemon</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <UserId>${escapeXml(userId)}</UserId>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>${escapeXml(userId)}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>${escapeXml(wscriptPath)}</Command>
      <Arguments>"${escapeXml(vbsPath)}"</Arguments>
    </Exec>
  </Actions>
</Task>
`;
}

function run(cmd, args) {
  try {
    const output = execFileSync(cmd, args, {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
      windowsHide: true,
    });
    return { ok: true, output: output.trim() };
  } catch (err) {
    return { ok: false, output: (err.stderr || err.stdout || err.message || '').trim() };
  }
}

function runPowerShell(script) {
  return run('powershell.exe', [
    '-NoProfile',
    '-NonInteractive',
    '-ExecutionPolicy',
    'Bypass',
    '-Command',
    script,
  ]);
}

// $ErrorActionPreference='Stop' turns cmdlet failures into the catch block's exit 1,
// since -Command otherwise exits 0 even after a non-terminating error.
function psTry(scriptLines) {
  return [
    "$ErrorActionPreference = 'Stop'",
    'try {',
    ...scriptLines.map(line => `  ${line}`),
    '  exit 0',
    '} catch {',
    '  [Console]::Error.WriteLine($_.Exception.Message)',
    '  exit 1',
    '}',
  ].join('\n');
}

function taskExists() {
  const result = runPowerShell(
    `if (Get-ScheduledTask -TaskName ${psString(SERVICE_NAME)} -ErrorAction SilentlyContinue) { exit 0 } else { exit 1 }`,
  );
  return result.ok;
}

function windowsUserId() {
  const domain = process.env.USERDOMAIN?.trim();
  const user = process.env.USERNAME?.trim();
  if (domain && user) return `${domain}\\${user}`;
  const result = run('whoami', []);
  return result.ok ? result.output : null;
}

// The cmd wrapper is the install-time record of the exact node invocation, so
// process matching only ever hits the task's own daemon — never a foreground
// `vibe-usage daemon` running from a different checkout. No end anchor: the
// line continues with the daemon.log redirection.
function readTaskBinPath(paths) {
  try {
    const cmd = readFileSync(paths.cmd, 'utf-8');
    return cmd.match(/^"[^"]+" "([^"]+)" daemon\b/m)?.[1] || null;
  } catch {
    return null;
  }
}

// -like treats []*? as wildcards; a literal path containing any of them must be
// bracket-escaped to still match
function psLikeFragment(value) {
  return value.replace(/[[\]*?]/g, '[$&]');
}

function daemonProcessKillLines(binPath) {
  if (!binPath) return [];
  const pattern = `'*${psLikeFragment(binPath)}* daemon*'`;
  return [
    `Get-CimInstance Win32_Process -Filter "Name='node.exe'" |`,
    `  Where-Object { $_.CommandLine -like ${pattern} } |`,
    '  ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }',
  ];
}

function install() {
  const plat = detectPlatform();
  if (!plat) {
    console.log(failure('当前平台不支持 daemon。'));
    console.log(dim('  支持: Linux (systemd) / macOS (launchd) / Windows (Task Scheduler)'));
    return;
  }

  const { nodePath, binPath, isNpxCache } = resolvePaths();

  if (isNpxCache) {
    console.log(warn('检测到从 npx 缓存运行 vibe-usage,缓存清理后 daemon 会失效。'));
    console.log(dim('  建议先全局安装:  npm install -g @vibe-cafe/vibe-usage'));
    console.log();
  }

  const paths = getServicePaths(plat);

  // A leftover daemon-task.xml without a registration (crashed uninstall) must
  // not block a fresh install, so Task Scheduler checks the live task instead
  const alreadyInstalled = plat === 'taskscheduler' ? taskExists() : existsSync(paths.file);
  if (alreadyInstalled) {
    console.log(warn('Daemon 已安装，运行 `vibe-usage daemon restart` 或 `uninstall` 先处理。'));
    return;
  }

  mkdirSync(paths.dir, { recursive: true });

  if (plat === 'systemd') {
    writeFileSync(paths.file, generateSystemdUnit(nodePath, binPath), 'utf-8');
    console.log(dim(`  已写入 ${paths.file}`));

    run('systemctl', ['--user', 'daemon-reload']);
    const result = run('systemctl', ['--user', 'enable', '--now', `${SERVICE_NAME}.service`]);
    if (!result.ok) {
      console.error(failure(`启动服务失败: ${result.output}`));
      return;
    }
    console.log(success('服务已启用并启动。'));
  }

  if (plat === 'launchd') {
    mkdirSync(join(homedir(), '.vibe-usage'), { recursive: true });
    writeFileSync(paths.file, generateLaunchdPlist(nodePath, binPath), 'utf-8');
    console.log(dim(`  已写入 ${paths.file}`));

    const result = run('launchctl', ['load', paths.file]);
    if (!result.ok) {
      console.error(failure(`加载服务失败: ${result.output}`));
      return;
    }
    console.log(success('服务已加载并启动。'));
  }

  if (plat === 'taskscheduler') {
    const userId = windowsUserId();
    if (!userId) {
      console.error(failure('无法确定当前 Windows 用户，安装中止。'));
      return;
    }
    const wscriptPath = join(
      process.env.WINDIR?.trim() || process.env.SystemRoot?.trim() || 'C:\\Windows',
      'System32',
      'wscript.exe',
    );

    writeFileSync(paths.cmd, generateWindowsTaskCmd(nodePath, binPath), 'utf-8');
    writeFileSync(paths.vbs, generateWindowsTaskVbs(paths.cmd), 'utf-8');
    writeFileSync(paths.file, generateWindowsTaskXml(userId, wscriptPath, paths.vbs), 'utf-8');
    console.log(dim(`  已写入 ${paths.file}`));

    // Get-Content must force UTF8: the XML is written without a BOM and default
    // decoding on e.g. zh-CN systems is ANSI, which mangles non-ASCII paths
    const result = runPowerShell(psTry([
      `Register-ScheduledTask -TaskName ${psString(SERVICE_NAME)} -Xml (Get-Content -Raw -Encoding UTF8 ${psString(paths.file)}) -Force | Out-Null`,
      `Start-ScheduledTask -TaskName ${psString(SERVICE_NAME)}`,
    ]));
    if (!result.ok) {
      console.error(failure(`注册/启动计划任务失败: ${result.output}`));
      return;
    }
    console.log(success('计划任务已注册并启动。'));
  }

  console.log();
  console.log(success('Daemon 已安装，用量数据将每 30 分钟自动同步。'));
  console.log(dim('  运行 `vibe-usage daemon status` 查看状态。'));
}

function uninstall() {
  const plat = detectPlatform();
  if (!plat) {
    console.log(failure('未检测到支持的服务平台。'));
    return;
  }

  const paths = getServicePaths(plat);

  const installed = plat === 'taskscheduler'
    ? taskExists() || existsSync(paths.file)
    : existsSync(paths.file);
  if (!installed) {
    console.log(dim('未安装 daemon 服务。'));
    return;
  }

  if (plat === 'systemd') {
    run('systemctl', ['--user', 'stop', `${SERVICE_NAME}.service`]);
    run('systemctl', ['--user', 'disable', `${SERVICE_NAME}.service`]);
    unlinkSync(paths.file);
    run('systemctl', ['--user', 'daemon-reload']);
    console.log(success('服务已停止、禁用并删除。'));
  }

  if (plat === 'launchd') {
    run('launchctl', ['unload', paths.file]);
    unlinkSync(paths.file);
    console.log(success('服务已卸载并删除。'));
  }

  if (plat === 'taskscheduler') {
    if (taskExists()) {
      const result = runPowerShell(psTry([
        `Stop-ScheduledTask -TaskName ${psString(SERVICE_NAME)} -ErrorAction SilentlyContinue`,
        ...daemonProcessKillLines(readTaskBinPath(paths)),
        `Unregister-ScheduledTask -TaskName ${psString(SERVICE_NAME)} -Confirm:$false`,
      ]));
      if (!result.ok) {
        console.error(failure(`删除计划任务失败: ${result.output}`));
        return;
      }
    }
    for (const file of [paths.file, paths.cmd, paths.vbs]) {
      if (existsSync(file)) unlinkSync(file);
    }
    console.log(success('服务已卸载并删除。'));
  }
}

function status() {
  const plat = detectPlatform();
  if (!plat) {
    console.log(failure('未检测到支持的服务平台。'));
    return;
  }

  const paths = getServicePaths(plat);

  if (plat === 'taskscheduler') {
    if (!taskExists()) {
      console.log(dim('未安装 daemon 服务。'));
      console.log(dim('  运行 `vibe-usage daemon install` 安装。'));
      return;
    }
    const binPath = readTaskBinPath(paths);
    const scriptLines = [
      `$t = Get-ScheduledTask -TaskName ${psString(SERVICE_NAME)} -ErrorAction SilentlyContinue`,
      'if (-not $t) { exit 1 }',
      'Write-Output ("State=" + $t.State)',
    ];
    if (binPath) {
      const pattern = `'*${psLikeFragment(binPath)}* daemon*'`;
      scriptLines.push(
        `$p = Get-CimInstance Win32_Process -Filter "Name='node.exe'" | Where-Object { $_.CommandLine -like ${pattern} } | Select-Object -First 1`,
        'if ($p) { Write-Output "DaemonProcess=running" } else { Write-Output "DaemonProcess=stopped" }',
      );
    }
    scriptLines.push(
      '$i = Get-ScheduledTaskInfo -TaskName ' + psString(SERVICE_NAME) + ' -ErrorAction SilentlyContinue',
      'if ($i -and $i.LastRunTime.Year -gt 1) { Write-Output ("LastRunTime=" + $i.LastRunTime.ToString("s")) }',
      'if ($i) { Write-Output ("LastTaskResult=" + $i.LastTaskResult) }',
    );
    const result = runPowerShell(scriptLines.join('\n'));
    if (!result.ok) {
      console.log(warn('无法读取计划任务状态。'));
      return;
    }
    const lines = Object.fromEntries(result.output
      .split(/\r?\n/)
      .map(line => line.trim())
      .filter(Boolean)
      .map(line => {
        const idx = line.indexOf('=');
        return idx === -1 ? [line, ''] : [line.slice(0, idx), line.slice(idx + 1)];
      }));
    // The live node process is the source of truth; the task State can lag
    const running = binPath
      ? lines.DaemonProcess === 'running'
      : lines.State === 'Running';
    if (running) {
      console.log(success('服务运行中。'));
    } else if (lines.State === 'Ready' || lines.State === 'Stopped' || lines.State === 'Running') {
      console.log(warn('服务已安装但当前未运行。'));
    } else {
      console.log(warn(`服务状态异常: ${lines.State || '未知'}`));
    }
    for (const key of ['LastRunTime', 'LastTaskResult']) {
      if (lines[key]) console.log(dim(`  ${key}=${lines[key]}`));
    }
    if (!running) {
      console.log(dim(`  查看日志: ${join(homedir(), '.vibe-usage', 'daemon.log')}，或运行 \`vibe-usage daemon restart\`。`));
    }
    return;
  }

  if (!existsSync(paths.file)) {
    console.log(dim('未安装 daemon 服务。'));
    console.log(dim('  运行 `vibe-usage daemon install` 安装。'));
    return;
  }

  if (plat === 'systemd') {
    const result = run('systemctl', ['--user', 'status', `${SERVICE_NAME}.service`]);
    console.log(dim(result.output));
  }

  if (plat === 'launchd') {
    const result = run('launchctl', ['list', LAUNCHD_LABEL]);
    if (result.ok) {
      console.log(dim(`Service: ${LAUNCHD_LABEL}`));
      console.log(dim(result.output));
    } else {
      console.log(warn('服务已安装但当前未运行。'));
    }
  }
}

function stop() {
  const plat = detectPlatform();
  if (!plat) {
    console.log(failure('未检测到支持的服务平台。'));
    return;
  }

  if (plat === 'systemd') {
    const result = run('systemctl', ['--user', 'stop', `${SERVICE_NAME}.service`]);
    console.log(result.ok ? success('服务已停止。') : failure(`停止失败: ${result.output}`));
  }

  if (plat === 'launchd') {
    // The plist sets KeepAlive=true, so `launchctl stop` is useless here —
    // launchd immediately relaunches the job and the daemon keeps running.
    // unload removes the job from launchd entirely; the plist file stays on
    // disk, so `daemon restart` (load) and status detection keep working.
    const paths = getServicePaths(plat);
    if (!existsSync(paths.file)) {
      console.log(dim('未安装 daemon 服务。'));
      return;
    }
    const result = run('launchctl', ['unload', paths.file]);
    console.log(result.ok ? success('服务已停止。') : failure(`停止失败: ${result.output}`));
  }

  if (plat === 'taskscheduler') {
    if (!taskExists()) {
      console.log(dim('未安装 daemon 服务。'));
      return;
    }
    // The logon trigger stays registered, so like launchd's unload the daemon
    // stays stopped until `restart` or the next logon. Stop-ScheduledTask only
    // terminates the wscript wrapper, so the real node daemon is matched and
    // killed explicitly.
    const paths = getServicePaths(plat);
    const binPath = readTaskBinPath(paths);
    const result = runPowerShell(psTry([
      `Stop-ScheduledTask -TaskName ${psString(SERVICE_NAME)} -ErrorAction SilentlyContinue`,
      ...daemonProcessKillLines(binPath),
    ]));
    console.log(result.ok ? success('服务已停止。') : failure(`停止失败: ${result.output}`));
  }
}

function restart() {
  const plat = detectPlatform();
  if (!plat) {
    console.log(failure('未检测到支持的服务平台。'));
    return;
  }

  if (plat === 'systemd') {
    const result = run('systemctl', ['--user', 'restart', `${SERVICE_NAME}.service`]);
    console.log(result.ok ? success('服务已重启。') : failure(`重启失败: ${result.output}`));
  }

  if (plat === 'launchd') {
    // unload + load (not stop + start): stop can't win against KeepAlive, and
    // load re-runs the job immediately thanks to RunAtLoad=true.
    const paths = getServicePaths(plat);
    run('launchctl', ['unload', paths.file]);
    const result = run('launchctl', ['load', paths.file]);
    console.log(result.ok ? success('服务已重启。') : failure(`重启失败: ${result.output}`));
  }

  if (plat === 'taskscheduler') {
    if (!taskExists()) {
      console.log(dim('未安装 daemon 服务。'));
      return;
    }
    const paths = getServicePaths(plat);
    const binPath = readTaskBinPath(paths);
    const taskName = psString(SERVICE_NAME);
    const result = runPowerShell(psTry([
      `$t = Get-ScheduledTask -TaskName ${taskName}`,
      "if ($t.State -eq 'Running') {",
      `  Stop-ScheduledTask -TaskName ${taskName} -ErrorAction SilentlyContinue`,
      ...daemonProcessKillLines(binPath),
      '  $deadline = (Get-Date).AddSeconds(5)',
      `  while ((Get-ScheduledTask -TaskName ${taskName}).State -eq 'Running' -and (Get-Date) -lt $deadline) { Start-Sleep -Milliseconds 200 }`,
      '}',
      `Start-ScheduledTask -TaskName ${taskName}`,
    ]));
    console.log(result.ok ? success('服务已重启。') : failure(`重启失败: ${result.output}`));
  }
}

const SUBCOMMANDS = { install, uninstall, status, stop, restart };

export async function manageDaemon(subcommand) {
  const fn = SUBCOMMANDS[subcommand];
  if (!fn) {
    console.error(failure(`未知 daemon 子命令: ${subcommand}`));
    console.error(dim('  用法: vibe-usage daemon <install|uninstall|status|stop|restart>'));
    process.exit(1);
  }
  fn();
}
